sonar.projectKey=Learn-Jenkins-App
sonar.projectName=Learn Jenkins App
sonar.projectVersion=1.0

# Only scan the source code
sonar.sources=src

# Test files
sonar.tests=src

# Exclude unnecessary folders
sonar.exclusions=**/node_modules/**,**/build/**,**/.git/**,**/.netlify/**,**/test-results/**,**/e2e/**

# Identify test files
sonar.test.inclusions=src/**/*.test.js

sonar.sourceEncoding=UTF-8